### ISSUE TITLE
go module declared vs required path

### ISSUE THREAD

**Issue by nicksherron** [couchbase/gocb-opentelemetry#1]
```bash
$ go get github.com/couchbase/gocb-opentelemetry
go get: github.com/couchbase/gocb-opentelemetry@none updating to
        github.com/couchbase/gocb-opentelemetry@v0.0.0-20210630081352-2a8b0e1a37fd: parsing go.mod:
        module declares its path as: github.com/couchbase/gocbopentelemetry
                but was required as: github.com/couchbase/gocb-opentelemetry
```

btw thanks for making this @chvck

**Comment by chvck** [comment]
Thanks for raising this, I'll get that fixed up.

**Comment by chvck** [comment]
I think that this should now be fixed although locally I've had to do `go get github.com/couchbase/gocb-opentelemetry@master` to get it pull in the latest change - not entirely sure why...

Note - usage requires a very recent (not yet released) version of gocb due to requiring the new metrics and tracing interfaces exposed by gocb.
